/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Airplane.glb -T 
Files: Airplane.glb [377.65KB] > F:\My Documents\Sites\games\eager-eagle\public\models\Airplane-transformed.glb [39.24KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelAirplane(props) {
  const { nodes, materials } = useGLTF('models/Airplane-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry} material={materials.plane} />
    </group>
  )
}

useGLTF.preload('models/Airplane-transformed.glb')
