/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Blimp.glb -T 
Files: Blimp.glb [359.96KB] > F:\My Documents\Sites\games\eager-eagle\public\models\Blimp-transformed.glb [36.28KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelBlimp(props) {
  const { nodes, materials } = useGLTF('models/Blimp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.c.geometry} material={materials.lambert4SG} />
    </group>
  )
}

useGLTF.preload('models/Blimp-transformed.glb')
