/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Building 1-transformed.glb 
*/

import React, { useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useBox } from '@react-three/cannon'
import * as THREE from 'three'

export function ModelBuildingOne(props) {
  const { nodes, materials } = useGLTF('models/Building 1-transformed.glb')

  const { args, offset } = useMemo(() => {
    const geometry = nodes.skyscraper.geometry
    geometry.computeBoundingBox()
    const size = new THREE.Vector3()
    geometry.boundingBox.getSize(size)
    const center = new THREE.Vector3()
    geometry.boundingBox.getCenter(center)
    return { args: [size.x, size.y, size.z], offset: center }
  }, [nodes])

  const [ref, api] = useBox(() => ({
    mass: 0,
    type: 'Kinematic',
    args: args,
    position: props.position || [0, 0, 0],
    collisionFilterGroup: 2, // Group 2 (rocks/buildings)
    ...props
  }))

  React.useEffect(() => {
      if (props.position) {
          api.position.set(...props.position)
      }
  }, [props.position, api])

  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[-offset.x, -offset.y, -offset.z]}>
        <mesh geometry={nodes.skyscraper.geometry} material={materials.None} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Building 1-transformed.glb')