/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Helicopter.glb -T 
Files: Helicopter.glb [69.22KB] > F:\My Documents\Sites\games\eager-eagle\public\models\Helicopter-transformed.glb [9.49KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelHelicopter(props) {
  const { nodes, materials } = useGLTF('models/Helicopter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Box20180.geometry} material={materials['02___Default']} />
      <mesh geometry={nodes.Box20181.geometry} material={materials._crayfishdiffuse} />
      <mesh geometry={nodes.Object013_1.geometry} material={materials['03___Default']} />
      <mesh geometry={nodes.Object013_1_1.geometry} material={materials['07___Default']} />
    </group>
  )
}

useGLTF.preload('models/Helicopter-transformed.glb')
