/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Mountain Group.glb -T 
Files: Mountain Group.glb [58.43KB] > F:\My Documents\Sites\games\eager-eagle\public\models\Mountain Group-transformed.glb [7.94KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelMountainGroup(props) {
  const { nodes, materials } = useGLTF('models/Mountain Group-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Mountain_Group_2_1.geometry} material={materials.Stone} />
        <mesh geometry={nodes.Mountain_Group_2_2.geometry} material={materials.Snow} />
        <mesh geometry={nodes.Mountain_Group_2_3.geometry} material={materials.Dirt} />
      </group>
    </group>
  )
}

useGLTF.preload('models/Mountain Group-transformed.glb')
