/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Tree.gltf -T 
Files: Tree.gltf [211.35KB] > F:\My Documents\Sites\games\eager-eagle\public\models\Tree-transformed.glb [9.77KB] (95%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelTree(props) {
  const { nodes, materials } = useGLTF('models/Tree-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['tree-spruce'].geometry} material={materials.color_main} />
    </group>
  )
}

useGLTF.preload('models/Tree-transformed.glb')
