/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Flying saucer.glb -T 
Files: Flying saucer.glb [67.08KB] > F:\My Documents\Sites\games\eager-eagle\public\models\Flying saucer-transformed.glb [11.62KB] (83%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelUFO(props) {
  const { nodes, materials } = useGLTF('models/Flying saucer-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Flying_Saucer.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('models/Flying saucer-transformed.glb')
